name: OpenShift Deployer
description: OpenShift deployer with route verification or penetration testing
branding:
  icon: package
  color: blue

inputs:
  ### Required
  chart:
    description: Chart name
    required: true
  release:
    description: Release Name
    required: true
  repository:
    description: Specify a helm chart repository url or source path
    required: true
  oc_namespace:
    description: OpenShift namespace (e.g. abc123-dev)
    required: true
  oc_server:
    description: OpenShift server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  oc_token:
    description: OpenShift access token
    required: true
  values:
    description: Values to overwrite for helm chart
    required: false

runs:
  using: composite
  steps:
    # Process variables and inputs
    - name: Login
      shell: bash
      run: |
        # Allow pipefail, since we could be catching oc create errors
        set +o pipefail

        oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
        oc project ${{ inputs.oc_namespace }}
    - name: Install Helm
      shell: bash
      run: |
        # Allow pipefail, since we could be catching errors
        set +o pipefail

        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - name: Add Repository
      shell: bash
      run: |
        helm repo add ${{inputs.release}} ${{inputs.repository}}
    - name: Install Chart
      shell: bash
      run: |
        # Allow pipefail, since we could be catching errors
        set +o pipefail

        export VALUES="${{inputs.values}}"

        #Build --set string of values 
        for value in $VALUES
        do
          export SETVALUES+="--set $value "
        done

        if  [ helm upgrade ${{ inputs.release }} ${{ inputs.release }}/${{ inputs.chart }} $SETVALUES ] && [ helm upgrade ${{ inputs.release }} ${{ inputs.repository}}/${{ inputs.chart }} $SETVALUES]
        then
          if [ ! helm install ${{ inputs.release }} ${{ inputs.release }}/${{ inputs.chart }} $SETVALUES ]
          then
            helm install ${{ inputs.release }} ${{ inputs.repository }}/${{ inputs.chart }} $SETVALUES
          fi
        fi
